// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoservice

import (
	"context"

	"nulltv/rpc_service/video/pb/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ParseReq  = video.ParseReq
	ParseResp = video.ParseResp

	VideoService interface {
		Parse(ctx context.Context, in *ParseReq, opts ...grpc.CallOption) (*ParseResp, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) Parse(ctx context.Context, in *ParseReq, opts ...grpc.CallOption) (*ParseResp, error) {
	client := video.NewVideoServiceClient(m.cli.Conn())
	return client.Parse(ctx, in, opts...)
}
