version: "3.0"

networks:
  web-network:           # 网络
    driver: bridge    # 桥接模式

services:
  # chat_service:
  #   build: 
  #     context: ./  # 将项目根目录作为构建上下文
  #     dockerfile: ./chat_service/Dockerfile
  #   ports:
  #     - "8889:8889"
  #   container_name: chat_service
  #   networks:
  #     - web-network

  # http_service:
  #   restart: always
  #   build: 
  #     context: ./ 
  #     dockerfile: ./http_service/Dockerfile
  #   image: http_service:1.0
  #   ports:
  #     - "8888:8888"
  #   container_name: http_service
  #   networks:
  #     - web-network

  # rpc_user:
  #   build: 
  #     context: ./  
  #     dockerfile: ./rpc_service/webset/Dockerfile
  #   ports:
  #     - "8083:8083"
  #   container_name: rpc_user
    
  # rpc_webset:
  #   build: 
  #     context: ./ 
  #     dockerfile: ./rpc_service/webset/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   container_name: rpc_webset

  # etcd:
  #   image: bitnami/etcd:latest  # 镜像k
  #   container_name: etcd       # 容器名 --name
  #   restart: always             # 总是重启
  #   networks:
  #     - web-network                # 使用的网络 --network
  #   ports:                      # 端口映射 -p
  #     - "2379:2379"
  #     - "2380:2380"
  #   environment:                # 环境变量 --env
  #     - ALLOW_NONE_AUTHENTICATION=yes                       # 允许不用密码登录
  #     - ETCD_NAME=etcd                                     # etcd 的名字
  #     # - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380  # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
  #     # - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380           # 用于监听伙伴通讯的URL列表
  #     - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379         # 用于监听客户端通讯的URL列表
  #     - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379        # 列出这个成员的客户端URL，通告给集群中的其他成员
  #   volumes:
  #     - /data/null-links/etcd/data:/bitnami/etcd/data                            # 挂载的数据卷

  kafka:
    image: 'bitnami/kafka:3.6.2'
    container_name: kafka
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CREATE_TOPICS="validation-email:1:1,weblink-cover:1:1"
    networks:
      - web-network
    ports:
      - '9092:9092'
      - '9094:9094'
    volumes:
      - /data/null-links/kafka:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 9093:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: "TRUE"
    networks:
      - web-network

  minio:
    image: bitnami/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    privileged: true
    environment:
      MINIO_ROOT_USER: admin    #管理后台用户名
      MINIO_ROOT_PASSWORD: admin123 #管理后台密码，最小8个字符
    volumes:
      - /data/null-links/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /data/null-links/minio/config:/root/.minio/     #映射配置目录
    # command: server /data
    restart: always
    container_name: minio

  redis:
    image: redis:4.0.1
    container_name: redis
    volumes:
      - /data/null-links/redis/datadir:/data
      - /data/null-links/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/null-links/redis/logs:/logs
    command: redis-server
    ports:
      - 6379:6379