
DataSource: root:123456@tcp(192.168.0.50:3306)/db_null_links?charset=utf8mb4&parseTime=true

MinIO:
  EndPoint: "192.168.0.50:9000"
  AccessKeyID: "swjTlz02UIYY7iXCyCQM"
  SecretAccessKey: "ayNq4sY19U9PM9TTBFuGKKvP62h6kfNpYx4DQeb5"
  UseSSL: false
  DownloadHost: "http://192.168.0.50:9000"

WlCoverKqConsumser:
  Name: kq
  Brokers:
  - 192.168.0.50:9092
  Group: nl_consumer
  Topic: weblink-cover
  Offset: first
  Consumers: 1