Log:
  ServiceName: "weblink_cover"
  # Mode: "console"
  Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs/kq_consumer/weblink_cover"

DataSource: admin:pLabc@tcp(43.139.0.182:3306)/db_null_links?charset=utf8mb4&parseTime=true

MinIO:
  EndPoint: "10.0.0.5:9000"
  AccessKeyID: "UKrp44MZWBoZRQZTTHbu"
  SecretAccessKey: "p4NcdI8gMZDaf4gNUthKcieVoodVbFWjXsMjYZBu"
  UseSSL: false
  DownloadHost: "http://pic.null-links.com"

WlCoverKqConsumser:
  Name: kq
  Brokers:
  - 10.0.0.5:9092
  Group: nl_consumer
  Topic: weblink-cover
  Offset: first
  Consumers: 1