Log:
  ServiceName: "chat_service"
  Mode: "console"
  # Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/kq_consumer/weblink_cover/logs"

DataSource: root:123456@tcp(10.63.180.57:3306)/db_null_links?charset=utf8mb4&parseTime=true

MinIO:
  EndPoint: "10.63.180.57:9000"
  AccessKeyID: "swjTlz02UIYY7iXCyCQM"
  SecretAccessKey: "ayNq4sY19U9PM9TTBFuGKKvP62h6kfNpYx4DQeb5"
  UseSSL: false
  DownloadHost: "http://10.63.180.57:9000"

WlCoverKqConsumser:
  Name: kq
  Brokers:
  - 10.63.180.57:9092
  Group: nl_consumer
  Topic: weblink-cover
  Offset: first
  Consumers: 1
