Log:
  ServiceName: "weblink_cover"
  # Mode: "console"
  Mode: "file"
  Encoding: "plain"
  Level: "info"
  Path: "/data/logs/kq_consumer/weblink_cover"

DataSource: admin:pL%al8oB5c@tcp(43.139.0.182:3306)/db_null_links?charset=utf8mb4&parseTime=true

MinIO:
  EndPoint: "43.128.2.203:9000"
  AccessKeyID: "JXhP9O5DxAdqLNMxln0R"
  SecretAccessKey: "xGihi168kR4FyBAWTAZNCeVxDHajIKgMX71xv9tB"
  UseSSL: false
  DownloadHost: "http://pic.null-links.com"

WlCoverKqConsumser:
  Name: kq
  Brokers:
  - 192.168.0.50:9092
  Group: nl_consumer
  Topic: weblink-cover
  Offset: first
  Consumers: 1