// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: rpc_service/content_security/content_security.proto

package content_security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsetCheckQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *WebsetCheckQueryReq) Reset() {
	*x = WebsetCheckQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_content_security_content_security_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsetCheckQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsetCheckQueryReq) ProtoMessage() {}

func (x *WebsetCheckQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_content_security_content_security_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsetCheckQueryReq.ProtoReflect.Descriptor instead.
func (*WebsetCheckQueryReq) Descriptor() ([]byte, []int) {
	return file_rpc_service_content_security_content_security_proto_rawDescGZIP(), []int{0}
}

func (x *WebsetCheckQueryReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WebsetCheckQueryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *WebsetCheckQueryReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WebsetCheckQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *WebsetCheckQueryResp) Reset() {
	*x = WebsetCheckQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_content_security_content_security_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsetCheckQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsetCheckQueryResp) ProtoMessage() {}

func (x *WebsetCheckQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_content_security_content_security_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsetCheckQueryResp.ProtoReflect.Descriptor instead.
func (*WebsetCheckQueryResp) Descriptor() ([]byte, []int) {
	return file_rpc_service_content_security_content_security_proto_rawDescGZIP(), []int{1}
}

func (x *WebsetCheckQueryResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *WebsetCheckQueryResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type WebsetCheckConfirmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	WebsetId int64  `protobuf:"varint,2,opt,name=webset_id,json=websetId,proto3" json:"webset_id,omitempty"`
	Action   int32  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *WebsetCheckConfirmReq) Reset() {
	*x = WebsetCheckConfirmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_content_security_content_security_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsetCheckConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsetCheckConfirmReq) ProtoMessage() {}

func (x *WebsetCheckConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_content_security_content_security_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsetCheckConfirmReq.ProtoReflect.Descriptor instead.
func (*WebsetCheckConfirmReq) Descriptor() ([]byte, []int) {
	return file_rpc_service_content_security_content_security_proto_rawDescGZIP(), []int{2}
}

func (x *WebsetCheckConfirmReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WebsetCheckConfirmReq) GetWebsetId() int64 {
	if x != nil {
		return x.WebsetId
	}
	return 0
}

func (x *WebsetCheckConfirmReq) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type WebsetCheckConfirmResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *WebsetCheckConfirmResp) Reset() {
	*x = WebsetCheckConfirmResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_content_security_content_security_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsetCheckConfirmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsetCheckConfirmResp) ProtoMessage() {}

func (x *WebsetCheckConfirmResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_content_security_content_security_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsetCheckConfirmResp.ProtoReflect.Descriptor instead.
func (*WebsetCheckConfirmResp) Descriptor() ([]byte, []int) {
	return file_rpc_service_content_security_content_security_proto_rawDescGZIP(), []int{3}
}

func (x *WebsetCheckConfirmResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *WebsetCheckConfirmResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_rpc_service_content_security_content_security_proto protoreflect.FileDescriptor

var file_rpc_service_content_security_content_security_proto_rawDesc = []byte{
	0x0a, 0x33, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x22, 0x5c, 0x0a, 0x13, 0x57, 0x65, 0x62, 0x73, 0x65,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x22, 0x62, 0x0a,
	0x15, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x65, 0x62, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x77, 0x65, 0x62, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x58, 0x0a, 0x16, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x32, 0xe4, 0x01, 0x0a, 0x16,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x65,
	0x62, 0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x67, 0x0a, 0x12, 0x57, 0x65, 0x62,
	0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12,
	0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x65, 0x62, 0x73,
	0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_service_content_security_content_security_proto_rawDescOnce sync.Once
	file_rpc_service_content_security_content_security_proto_rawDescData = file_rpc_service_content_security_content_security_proto_rawDesc
)

func file_rpc_service_content_security_content_security_proto_rawDescGZIP() []byte {
	file_rpc_service_content_security_content_security_proto_rawDescOnce.Do(func() {
		file_rpc_service_content_security_content_security_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_service_content_security_content_security_proto_rawDescData)
	})
	return file_rpc_service_content_security_content_security_proto_rawDescData
}

var file_rpc_service_content_security_content_security_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_service_content_security_content_security_proto_goTypes = []interface{}{
	(*WebsetCheckQueryReq)(nil),    // 0: content_security.WebsetCheckQueryReq
	(*WebsetCheckQueryResp)(nil),   // 1: content_security.WebsetCheckQueryResp
	(*WebsetCheckConfirmReq)(nil),  // 2: content_security.WebsetCheckConfirmReq
	(*WebsetCheckConfirmResp)(nil), // 3: content_security.WebsetCheckConfirmResp
}
var file_rpc_service_content_security_content_security_proto_depIdxs = []int32{
	0, // 0: content_security.ContentSecurityService.WebsetCheckQuery:input_type -> content_security.WebsetCheckQueryReq
	2, // 1: content_security.ContentSecurityService.WebsetCheckConfirm:input_type -> content_security.WebsetCheckConfirmReq
	1, // 2: content_security.ContentSecurityService.WebsetCheckQuery:output_type -> content_security.WebsetCheckQueryResp
	3, // 3: content_security.ContentSecurityService.WebsetCheckConfirm:output_type -> content_security.WebsetCheckConfirmResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_service_content_security_content_security_proto_init() }
func file_rpc_service_content_security_content_security_proto_init() {
	if File_rpc_service_content_security_content_security_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_service_content_security_content_security_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsetCheckQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_content_security_content_security_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsetCheckQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_content_security_content_security_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsetCheckConfirmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_content_security_content_security_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsetCheckConfirmResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_service_content_security_content_security_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_content_security_content_security_proto_goTypes,
		DependencyIndexes: file_rpc_service_content_security_content_security_proto_depIdxs,
		MessageInfos:      file_rpc_service_content_security_content_security_proto_msgTypes,
	}.Build()
	File_rpc_service_content_security_content_security_proto = out.File
	file_rpc_service_content_security_content_security_proto_rawDesc = nil
	file_rpc_service_content_security_content_security_proto_goTypes = nil
	file_rpc_service_content_security_content_security_proto_depIdxs = nil
}
