Name: http_service
Host: 0.0.0.0
Port: 8888

Log:
  ServiceName: "http_service"
  Mode: "console"
  Encoding: "plain"
  Level: "debug"
  Path: "http_service/logs"

Auth:
  AccessSecret: "AccessSecret"
  AccessExpire: 604800

# RPC
UserRpcConf:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: user.rpc
  NonBlock: true

WebsetRpcConf:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: webset.rpc
  NonBlock: true