Name: http_service
Host: 0.0.0.0
Port: 8888

Log:
  ServiceName: "http_service"
  # Mode: "console"
  Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs"

Auth:
  AccessSecret: "AccessSecret12"
  AccessExpire: 604800

# RPC
UserRpcConf:
  Target: {ipaddr}:8081
  # Etcd:
  #   Hosts:
  #     - {ipaddr}:2379
  #   Key: user.rpc
  # NonBlock: true

WebsetRpcConf:
  Target: {ipaddr}:8082
  # Etcd:
  #   Hosts:
  #     - {ipaddr}:2379
  #   Key: webset.rpc
  # NonBlock: true

MinIO:
  EndPoint: "{ipaddr}:9000"
  AccessKeyID: "swjTlz02UIYY7iXCyCQM"
  SecretAccessKey: "ayNq4sY19U9PM9TTBFuGKKvP62h6kfNpYx4DQeb5"
  UseSSL: false
  DownloadHost: "http://{ipaddr}:9000"