Name: http_service
Host: 0.0.0.0
Port: 8888

DataSource: root:123456@tcp(127.0.0.1:3306)/db_null_links?charset=utf8mb4&parseTime=true

Log:
  ServiceName: "http_service"
  Mode: "console"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs"

Auth:
  AccessSecret: "AccessSecret12"
  AccessExpire: 604800

# # RPC
# UserRpcConf:
#   Target: 127.0.0.1:8081
#   # Etcd:
#   #   Hosts:
#   #     - 127.0.0.1:2379
#   #   Key: user.rpc
#   # NonBlock: true

# WebsetRpcConf:
#   Target: 127.0.0.1:8082
#   # Etcd:
#   #   Hosts:
#   #     - 127.0.0.1:2379
#   #   Key: webset.rpc
#   # NonBlock: true

VdEmailKqPusherConf:
  Brokers:
    - 127.0.0.1:9094
  Topic: validation-email

WlCoverKqPusherConf:
  Brokers:
    - 127.0.0.1:9094
  Topic: weblink-cover

RedisConf:
  Host: "127.0.0.1:6379"
  Password: ""
  DB:   0

MinIO:
  EndPoint: "127.0.0.1:9000"
  AccessKeyID: "kx5GRzf9W8lrAu6L4yHa"
  SecretAccessKey: "yD4XtDdcQ7PtFkGXrFTCgc0VW2MsfhiX6AWpHFNH"
  UseSSL: false
  DownloadHost: "http://127.0.0.1:9000"

Email:
  SmtpDomain: "smtp.exmail.qq.com"
  Sender: "null-links-noreply@null-links.com"
  Password: "UwRQi9rTc4hxHKx4"
 

DefaultAvatarUrl: "https://pic.null-links.com/avatar/default.jpg"

DefaultWebsetCoverUrl: "https://pic.null-links.com/websetcover/default.jpg"

DefaultWeblinkCoverUrl: "https//pic.null-links.com/weblinkcover/default.jpg"