Mode: "debug"

Log:
  ServiceName: "chat_service"
  Mode: "console"
  # Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs/kq_consumer/validation_email"

VdEmailKqConsumser:
  Name: kq
  Brokers:
  - 10.63.180.57:9092
  Group: nl_consumer
  Topic: validation-email
  Offset: first
  Consumers: 1

email:
 SmtpDomain: "smtp.exmail.qq.com"
 Sender: "noreply@null-links.com"
 Password: "r5UbqseThNS6Dhqw"