Mode: "debug"

VdEmailKqConsumser:
  Name: kq
  Brokers:
  - 192.168.0.50:9092
  Group: nl_consumer
  Topic: validation-email
  Offset: first
  Consumers: 1

email:
 SmtpDomain: "smtp.163.com"
 Sender: "null_links@163.com"
 Password: "UKASRFRWQZFNUIAN"