Mode: "debug"

VdEmailKqConsumser:
  Name: kq
  Brokers:
  - 127.0.0.1:9094
  Group: nl_consumer
  Topic: validation-email
  Offset: first
  Consumers: 1

# email:
#  SmtpDomain: "smtp.163.com"
#  Sender: "null_links@163.com"
#  Password: "UKASRFRWQZFNUIAN"
email:
  SmtpDomain: "smtp.exmail.qq.com"
  Sender: "null-links-noreply@null-links.com"
  Password: "UwRQi9rTc4hxHKx4"
 