Mode: "online"

Log:
  ServiceName: "validation_email"
  # Mode: "console"
  Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs/kq_consumer/validation_email"

VdEmailKqConsumser:
  Name: kq
  Brokers:
  - 192.168.0.50:9092
  Group: nl_consumer
  Topic: validation-email
  Offset: first
  Consumers: 1

email:
 SmtpDomain: "smtp.exmail.qq.com"
 Sender: "noreply@null-links.com"
 Password: "r5UbqseThNS6Dhqw"