Name: chat_service
Host: 0.0.0.0
Port: 8889

Log:
  ServiceName: "chat_service"
  # Mode: "console"
  Mode: "file"
  Encoding: "plain"
  Level: "debug"
  Path: "/data/logs"

RedisConf:
  Host: "{ipaddr}:6379"
  Password: ""
  DB:   0

Auth:
  AccessSecret: "AccessSecret"
  AccessExpire: 604800

DataSource: root:123456@tcp({ipaddr}:3306)/db_null_links?charset=utf8mb4&parseTime=true

# RPC
UserRpcConf:
  Target: {ipaddr}:8081
  # Etcd:
  #   Hosts:
  #     - {ipaddr}:2379
  #   Key: user.rpc
  # NonBlock: true
