// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tFavoriteFieldNames          = builder.RawFieldNames(&TFavorite{})
	tFavoriteRows                = strings.Join(tFavoriteFieldNames, ",")
	tFavoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(tFavoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tFavoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(tFavoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tFavoriteModel interface {
		Insert(ctx context.Context, data *TFavorite) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TFavorite, error)
		Update(ctx context.Context, data *TFavorite) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTFavoriteModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TFavorite struct {
		Id        int64     `db:"id"`         // 主键id
		UserId    int64     `db:"user_id"`    // 用户id
		WebsetId  int64     `db:"webset_id"`  // 网页单id
		Status    int64     `db:"status"`     // 在库状态
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newTFavoriteModel(conn sqlx.SqlConn) *defaultTFavoriteModel {
	return &defaultTFavoriteModel{
		conn:  conn,
		table: "`t_favorite`",
	}
}

func (m *defaultTFavoriteModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTFavoriteModel) FindOne(ctx context.Context, id int64) (*TFavorite, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tFavoriteRows, m.table)
	var resp TFavorite
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTFavoriteModel) Insert(ctx context.Context, data *TFavorite) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tFavoriteRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.WebsetId, data.Status)
	return ret, err
}

func (m *defaultTFavoriteModel) Update(ctx context.Context, data *TFavorite) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tFavoriteRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.WebsetId, data.Status, data.Id)
	return err
}

func (m *defaultTFavoriteModel) tableName() string {
	return m.table
}
