// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLikeFieldNames          = builder.RawFieldNames(&TLike{})
	tLikeRows                = strings.Join(tLikeFieldNames, ",")
	tLikeRowsExpectAutoSet   = strings.Join(stringx.Remove(tLikeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLikeRowsWithPlaceHolder = strings.Join(stringx.Remove(tLikeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLikeModel interface {
		Insert(ctx context.Context, data *TLike) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLike, error)
		FindOneByUserIdWebsetId(ctx context.Context, userId int64, websetId int64) (*TLike, error)
		Update(ctx context.Context, data *TLike) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLikeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLike struct {
		Id        int64     `db:"id"`         // 主键id
		UserId    int64     `db:"user_id"`    // 用户id
		WebsetId  int64     `db:"webset_id"`  // 网页单id
		Status    int64     `db:"status"`     // 点赞状态
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newTLikeModel(conn sqlx.SqlConn) *defaultTLikeModel {
	return &defaultTLikeModel{
		conn:  conn,
		table: "`t_like`",
	}
}

func (m *defaultTLikeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLikeModel) FindOne(ctx context.Context, id int64) (*TLike, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLikeRows, m.table)
	var resp TLike
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLikeModel) FindOneByUserIdWebsetId(ctx context.Context, userId int64, websetId int64) (*TLike, error) {
	var resp TLike
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `webset_id` = ? limit 1", tLikeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, websetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLikeModel) Insert(ctx context.Context, data *TLike) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tLikeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.WebsetId, data.Status)
	return ret, err
}

func (m *defaultTLikeModel) Update(ctx context.Context, newData *TLike) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLikeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.WebsetId, newData.Status, newData.Id)
	return err
}

func (m *defaultTLikeModel) tableName() string {
	return m.table
}
