// Code generated by goctl. DO NOT EDIT.
// Source: content_security.proto

package server

import (
	"context"

	"null-links/rpc_service/content_security/internal/logic"
	"null-links/rpc_service/content_security/internal/svc"
	"null-links/rpc_service/content_security/pb/content_security"
)

type ContentSecurityServiceServer struct {
	svcCtx *svc.ServiceContext
	content_security.UnimplementedContentSecurityServiceServer
}

func NewContentSecurityServiceServer(svcCtx *svc.ServiceContext) *ContentSecurityServiceServer {
	return &ContentSecurityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentSecurityServiceServer) WebsetCheckQuery(ctx context.Context, in *content_security.WebsetCheckQueryReq) (*content_security.WebsetCheckQueryResp, error) {
	l := logic.NewWebsetCheckQueryLogic(ctx, s.svcCtx)
	return l.WebsetCheckQuery(in)
}

func (s *ContentSecurityServiceServer) WebsetCheckConfirm(ctx context.Context, in *content_security.WebsetCheckConfirmReq) (*content_security.WebsetCheckConfirmResp, error) {
	l := logic.NewWebsetCheckConfirmLogic(ctx, s.svcCtx)
	return l.WebsetCheckConfirm(in)
}
